kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: demo-rolebinding 
subjects:
- kind: ServiceAccount
  name: cred
roleRef:
  kind: Role
  name: demorole
  apiGroup: rbac.authorization.k8s.io

