apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-deploy-api-pipelinerun-
spec:
  serviceAccountName: cred
  pipelineRef:
    name: build-and-deploy
  params:
    - name: deployment-name
      value: sample-app
    - name: git-url
      value: https://github.com/savitaashture/devconf-cz-tekton-samples
    - name: IMAGE
      value: quay.io/savitaashture/devconfcz:latest
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 500Mi
